name: Tests (Preview)
'on':
  workflow_dispatch: null
  push:
    branches:
    - main
    - v[0-9].*[0-9].x
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
    paths:
    - haystack/preview/**/*.py
    - test/preview/**/*.py
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
  CORE_AZURE_CS_ENDPOINT: ${{ secrets.CORE_AZURE_CS_ENDPOINT }}
  CORE_AZURE_CS_API_KEY: ${{ secrets.CORE_AZURE_CS_API_KEY }}
  PYTHON_VERSION: '3.8'
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Black
      run: 'pip install --upgrade pip

        pip install .[formatting]

        '
    - name: Check status
      run: "if ! black . --check; then\n  git status\n  echo \"###################################################################################################\"\
        \n  echo \"# \"\n  echo \"# CHECK FAILED! Black found issues with your code\
        \ formatting.\"\n  echo \"# \"\n  echo \"# Either:\"\n  echo \"# 1. Run Black\
        \ locally before committing:\"\n  echo \"# \"\n  echo \"#     pip install\
        \ .[formatting]\"\n  echo \"#     black .\"\n  echo \"# \"\n  echo \"# 2.\
        \ Install the pre-commit hook:\"\n  echo \"# \"\n  echo \"#     pre-commit\
        \ install\"\n  echo \"# \"\n  echo \"# 3. See https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md\
        \ for help.\"\n  echo \"# \"\n  echo \"# If you have further problems, please\
        \ open an issue: https://github.com/deepset-ai/haystack/issues\"\n  echo \"\
        # \"\n  echo \"##################################################################################################\"\
        \n  exit 1\nfi\n"
    - name: Calculate alert data
      id: calculator
      shell: bash
      if: (success() || failure()) && github.ref_name == 'main'
      run: "if [ \"${{ job.status }}\" = \"success\" ]; then\n  echo \"alert_type=success\"\
        \ >> \"$GITHUB_OUTPUT\";\nelse\n  echo \"alert_type=error\" >> \"$GITHUB_OUTPUT\"\
        ;\nfi\n"
    - name: Send event to Datadog
      if: (success() || failure()) && github.ref_name == 'main'
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: "- title: \"${{ github.workflow }} workflow\"\n  text: \"Job ${{ github.job\
          \ }} in branch ${{ github.ref_name }}\"\n  alert_type: \"${{ steps.calculator.outputs.alert_type\
          \ }}\"\n  source_type_name: \"Github\"\n  host: ${{ github.repository_owner\
          \ }}\n  tags:\n    - \"project:${{ github.repository }}\"\n    - \"job:${{\
          \ github.job }}\"\n    - \"run_id:${{ github.run_id }}\"\n    - \"workflow:${{\
          \ github.workflow }}\"\n    - \"branch:${{ github.ref_name }}\"\n    - \"\
          url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id\
          \ }}\"\n"
  unit-tests:
    name: Unit / ${{ matrix.os }}
    needs: black
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Haystack
      run: 'pip install .[dev,preview] langdetect transformers[torch,sentencepiece]==4.34.1
        ''sentence-transformers>=2.2.0'' pypdf markdown-it-py mdit_plain tika ''azure-ai-formrecognizer>=3.2.0b2''

        pip install --no-deps llvmlite numba ''openai-whisper>=20230918''  # prevent
        outdated version of tiktoken pinned by openai-whisper

        '
    - name: Run
      run: pytest -m "unit" test/preview
    - name: Calculate alert data
      id: calculator
      shell: bash
      if: (success() || failure()) && github.ref_name == 'main'
      run: "if [ \"${{ job.status }}\" = \"success\" ]; then\n  echo \"alert_type=success\"\
        \ >> \"$GITHUB_OUTPUT\";\nelse\n  echo \"alert_type=error\" >> \"$GITHUB_OUTPUT\"\
        ;\nfi\n"
    - name: Send event to Datadog
      if: (success() || failure()) && github.ref_name == 'main'
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: "- title: \"${{ github.workflow }} workflow\"\n  text: \"Job ${{ github.job\
          \ }} in branch ${{ github.ref_name }}\"\n  alert_type: \"${{ steps.calculator.outputs.alert_type\
          \ }}\"\n  source_type_name: \"Github\"\n  host: ${{ github.repository_owner\
          \ }}\n  tags:\n    - \"project:${{ github.repository }}\"\n    - \"job:${{\
          \ github.job }}\"\n    - \"run_id:${{ github.run_id }}\"\n    - \"workflow:${{\
          \ github.workflow }}\"\n    - \"branch:${{ github.ref_name }}\"\n    - \"\
          url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id\
          \ }}\"\n"
  integration-tests-linux:
    name: Integration / ubuntu-latest
    needs: unit-tests
    runs-on: ubuntu-latest
    services:
      tika:
        image: apache/tika:2.9.0.0
        ports:
        - 9998:9998
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: 'sudo apt update

        sudo apt install ffmpeg  # for local Whisper tests

        '
    - name: Install Haystack
      run: 'pip install .[dev,preview] langdetect transformers[torch,sentencepiece]==4.34.1
        ''sentence-transformers>=2.2.0'' pypdf markdown-it-py mdit_plain tika ''azure-ai-formrecognizer>=3.2.0b2''

        pip install --no-deps llvmlite numba ''openai-whisper>=20230918''  # prevent
        outdated version of tiktoken pinned by openai-whisper

        '
    - name: Run
      run: pytest --maxfail=5 -m "integration" test/preview
    - name: Calculate alert data
      id: calculator
      shell: bash
      if: (success() || failure()) && github.ref_name == 'main'
      run: "if [ \"${{ job.status }}\" = \"success\" ]; then\n  echo \"alert_type=success\"\
        \ >> \"$GITHUB_OUTPUT\";\nelse\n  echo \"alert_type=error\" >> \"$GITHUB_OUTPUT\"\
        ;\nfi\n"
    - name: Send event to Datadog
      if: (success() || failure()) && github.ref_name == 'main'
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: "- title: \"${{ github.workflow }} workflow\"\n  text: \"Job ${{ github.job\
          \ }} in branch ${{ github.ref_name }}\"\n  alert_type: \"${{ steps.calculator.outputs.alert_type\
          \ }}\"\n  source_type_name: \"Github\"\n  host: ${{ github.repository_owner\
          \ }}\n  tags:\n    - \"project:${{ github.repository }}\"\n    - \"job:${{\
          \ github.job }}\"\n    - \"run_id:${{ github.run_id }}\"\n    - \"workflow:${{\
          \ github.workflow }}\"\n    - \"branch:${{ github.ref_name }}\"\n    - \"\
          url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id\
          \ }}\"\n"
  integration-tests-macos:
    name: Integration / macos-latest
    needs: unit-tests
    runs-on: macos-latest
    env:
      HAYSTACK_MPS_ENABLED: false
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: 'brew install ffmpeg  # for local Whisper tests

        brew install docker

        colima start

        '
    - name: Install Haystack
      run: 'pip install .[dev,preview] langdetect transformers[torch,sentencepiece]==4.34.1
        ''sentence-transformers>=2.2.0'' pypdf markdown-it-py mdit_plain tika ''azure-ai-formrecognizer>=3.2.0b2''

        pip install --no-deps llvmlite numba ''openai-whisper>=20230918''  # prevent
        outdated version of tiktoken pinned by openai-whisper

        '
    - name: Run Tika
      run: docker run -d -p 9998:9998 apache/tika:2.9.0.0
    - name: Run
      run: pytest --maxfail=5 -m "integration" test/preview
    - name: Calculate alert data
      id: calculator
      shell: bash
      if: (success() || failure()) && github.ref_name == 'main'
      run: "if [ \"${{ job.status }}\" = \"success\" ]; then\n  echo \"alert_type=success\"\
        \ >> \"$GITHUB_OUTPUT\";\nelse\n  echo \"alert_type=error\" >> \"$GITHUB_OUTPUT\"\
        ;\nfi\n"
    - name: Send event to Datadog
      if: (success() || failure()) && github.ref_name == 'main'
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: "- title: \"${{ github.workflow }} workflow\"\n  text: \"Job ${{ github.job\
          \ }} in branch ${{ github.ref_name }}\"\n  alert_type: \"${{ steps.calculator.outputs.alert_type\
          \ }}\"\n  source_type_name: \"Github\"\n  host: ${{ github.repository_owner\
          \ }}\n  tags:\n    - \"project:${{ github.repository }}\"\n    - \"job:${{\
          \ github.job }}\"\n    - \"run_id:${{ github.run_id }}\"\n    - \"workflow:${{\
          \ github.workflow }}\"\n    - \"branch:${{ github.ref_name }}\"\n    - \"\
          url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id\
          \ }}\"\n"
  integration-tests-windows:
    name: Integration / windows-latest
    needs: unit-tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Haystack
      run: 'pip install .[dev,preview] langdetect transformers[torch,sentencepiece]==4.34.1
        ''sentence-transformers>=2.2.0'' pypdf markdown-it-py mdit_plain tika ''azure-ai-formrecognizer>=3.2.0b2''

        pip install --no-deps llvmlite numba ''openai-whisper>=20230918''  # prevent
        outdated version of tiktoken pinned by openai-whisper

        '
    - name: Run
      run: pytest --maxfail=5 -m "integration" test/preview -k 'not tika'
    - name: Calculate alert data
      id: calculator
      shell: bash
      if: (success() || failure()) && github.ref_name == 'main'
      run: "if [ \"${{ job.status }}\" = \"success\" ]; then\n  echo \"alert_type=success\"\
        \ >> \"$GITHUB_OUTPUT\";\nelse\n  echo \"alert_type=error\" >> \"$GITHUB_OUTPUT\"\
        ;\nfi\n"
    - name: Send event to Datadog
      if: (success() || failure()) && github.ref_name == 'main'
      uses: masci/datadog@v1
      with:
        api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
        api-url: https://api.datadoghq.eu
        events: "- title: \"${{ github.workflow }} workflow\"\n  text: \"Job ${{ github.job\
          \ }} in branch ${{ github.ref_name }}\"\n  alert_type: \"${{ steps.calculator.outputs.alert_type\
          \ }}\"\n  source_type_name: \"Github\"\n  host: ${{ github.repository_owner\
          \ }}\n  tags:\n    - \"project:${{ github.repository }}\"\n    - \"job:${{\
          \ github.job }}\"\n    - \"run_id:${{ github.run_id }}\"\n    - \"workflow:${{\
          \ github.workflow }}\"\n    - \"branch:${{ github.ref_name }}\"\n    - \"\
          url:https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id\
          \ }}\"\n"
